language: python
python:
  - "3.6"
install: true  # override default install `pip install -r requirements.txt`
script: make test-$TEST_CMD
env:
  - TEST_CMD="sqlite" BOTO_CONFIG=/dev/null
  - TEST_CMD="flake8" BOTO_CONFIG=/dev/null
notifications:
  email:
    - ci-notify@fulfil.io
