language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
install: true  # override default install `pip install -r requirements.txt`
script: make test-$TEST_CMD
env:
  - TEST_CMD="sqlite"
  - TEST_CMD="flake8"
notifications:
  email:
    - ci-notify@fulfil.io
